-- 011_credit_purchases.sql
-- Log + Idempotenz für Stripe-Käufe. stripe_event_id UNIQUE → Webhook-Retries gutschreiben nie doppelt.

create table if not exists credit_purchases (
  id            bigint generated by default as identity primary key,
  stripe_event_id text unique not null,
  code          text,
  pack          text,
  credits       int,
  amount        int,            -- in kleinster Währungseinheit (Cent)
  currency      text,
  status        text,
  created_at    timestamptz not null default now()
);

create index if not exists credit_purchases_code_idx on credit_purchases (code);
alter table credit_purchases enable row level security;
